---
development:
  cloud_name: frankychau
  api_key: '428947978688597'
  api_secret: RIK4n8DmWbcHfNQKpxDaeSZRVfE
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: frankychau
  api_key: '428947978688597'
  api_secret: RIK4n8DmWbcHfNQKpxDaeSZRVfE
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: frankychau
  api_key: '428947978688597'
  api_secret: RIK4n8DmWbcHfNQKpxDaeSZRVfE
  enhance_image_tag: true
  static_image_support: false
